package com.SIGMA.USCO.notifications.entity.enums;

public enum NotificationType {

    MODALITY_STARTED,
    DOCUMENT_REVIEWED_BY_PROGRAM_HEAD,
    MODALITY_APPROVED_BY_PROGRAM_HEAD,
    MODALITY_APPROVED_BY_PROGRAM_CURRICULUM_COMMITTEE,
    MODALITY_FINAL_APPROVED_BY_COMMITTEE,
    MODALITY_REJECTED_BY_COMMITTEE,
    MODALITY_REJECTED,
    MODALITY_CANCELLATION_REQUESTED,
    MODALITY_CANCELLATION_APPROVED,
    MODALITY_CANCELLATION_REJECTED,
    MODALITY_CLOSED_BY_COMMITTEE,

    DOCUMENT_UPLOADED,
    DOCUMENT_CORRECTIONS_REQUESTED,
    CORRECTION_DEADLINE_REMINDER,
    CORRECTION_DEADLINE_EXPIRED,
    CORRECTION_RESUBMITTED,
    CORRECTION_APPROVED,
    CORRECTION_REJECTED_FINAL,

    DIRECTOR_ASSIGNED,
    EXAMINER_ASSIGNED,
    EXAMINER_FINAL_REVIEW_COMPLETED,

    DEFENSE_SCHEDULED,
    DEFENSE_COMPLETED,

    FINAL_APPROVED,

    MODALITY_INVITATION_RECEIVED,

    MODALITY_INVITATION_ACCEPTED,

    MODALITY_INVITATION_REJECTED,

    SEMINAR_STARTED,

    SEMINAR_CANCELLED,

    MODALITY_APPROVED_BY_EXAMINERS,

    DOCUMENT_REVIEW_TIEBREAKER_REQUIRED, // Decisión dividida de jurados: se requiere jurado de desempate

    READY_FOR_DEFENSE_REQUESTED, // Notificación cuando el estudiante solicita revisión de defensa

    MODALITY_READY_FOR_DEFENSE, // Jefatura aprobó los documentos finales y notificó a los jurados

    DIRECTOR_NOTIFIES_PROGRAM_HEAD_FINAL_REVIEW, // Director notifica a jefatura que docs finales están listos

    DOCUMENT_EDIT_REQUESTED,    // Estudiante solicita editar propuesta aprobada
    DOCUMENT_EDIT_APPROVED,     // Jurado aprueba la solicitud de edición
    DOCUMENT_EDIT_REJECTED      // Jurado rechaza la solicitud de edición

}
